services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    platform: linux/amd64
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - "./rabbitmq:/etc/pitstop/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/pitstop/rabbitmq.conf

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/amd64
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=8jkGh47hnDw89H@q8LN2

  mailserver:
    image: maildev/maildev:1.1.0
    platform: linux/amd64
    container_name: mailserver
    ports:
      - "25:25"
      - "4000:80"

  logserver:
    image: datalust/seq:latest
    platform: linux/amd64
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  vehiclemanagementapi:
    image: pitstop/vehiclemanagementapi:1.0
    platform: linux/amd64
    build: 
      context: VehicleManagementAPI
      platforms:
        - linux/amd64
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  customermanagementapi:
    image: pitstop/customermanagementapi:1.0
    platform: linux/amd64
    build:
      context: CustomerManagementAPI
      platforms:
        - linux/amd64
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  workshopmanagementapi:
    image: pitstop/workshopmanagementapi:1.0
    platform: linux/amd64
    build:
      context: WorkshopManagementAPI
      platforms:
        - linux/amd64
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  auditlogservice:
    image: pitstop/auditlogservice:1.0
    platform: linux/amd64
    build:
      context: AuditlogService
      platforms:
        - linux/amd64
    container_name: auditlogservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

  invoiceservice:
    image: pitstop/invoiceservice:1.0
    platform: linux/amd64
    build:
      context: InvoiceService
      platforms:
        - linux/amd64
    container_name: invoiceservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  notificationservice:
    image: pitstop/notificationservice:1.0
    platform: linux/amd64
    build:
      context: NotificationService
      platforms:
        - linux/amd64
    container_name: notificationservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  timeservice:
    image: pitstop/timeservice:1.0
    platform: linux/amd64
    build:
      context: TimeService
      platforms:
        - linux/amd64
    container_name: timeservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

  workshopmanagementeventhandler:
    image: pitstop/workshopmanagementeventhandler:1.0
    platform: linux/amd64
    build:
      context: WorkshopManagementEventHandler
      platforms:
        - linux/amd64
    container_name: workshopmanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production

  webapp:
    image: pitstop/webapp:1.0
    platform: linux/amd64
    build:
      context: WebApp
      platforms:
        - linux/amd64
    container_name: webapp
    depends_on:
      - customermanagementapi
      - vehiclemanagementapi
      - workshopmanagementapi
    ports:
      - "7005:7005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
