name: Build, Push, and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set kubectl context for AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'pitstop-resources'
          cluster-name: 'pitstop-lowcost-cluster'

      - name: Find Changed Service
        id: changed_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/**
          files_ignore: |
            src/k8s/**

      - name: Set Service Name and Path
        id: set_service
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          SERVICE_PATH_ORIGINAL=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | head -n 1 | cut -d'/' -f2)
          echo "service_name=${SERVICE_PATH_ORIGINAL,,}" >> $GITHUB_OUTPUT
          echo "service_path=${SERVICE_PATH_ORIGINAL}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, and Push to Docker Hub
        if: steps.changed_files.outputs.any_changed == 'true'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SERVICE_NAME: ${{ steps.set_service.outputs.service_name }}
          SERVICE_PATH: ${{ steps.set_service.outputs.service_path }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building service: $SERVICE_NAME from path: src/$SERVICE_PATH"
          docker build -t $DOCKERHUB_USERNAME/pitstop-$SERVICE_NAME:$IMAGE_TAG -f src/$SERVICE_PATH/Dockerfile src/$SERVICE_PATH
          docker push $DOCKERHUB_USERNAME/pitstop-$SERVICE_NAME:$IMAGE_TAG

      - name: Install and Deploy with Istio
        run: |
          curl -L https://istio.io/downloadIstio | sh -
          export PATH="$HOME/.istioctl/bin:$PATH"
          cd src/k8s/istio
          chmod +x *.sh
          ./install-istio.sh
          cd ../scripts
          chmod +x start-all.sh
          ./start-all.sh --istio