name: Build, Push, and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set kubectl context for AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'pitstop-resources'
          cluster-name: 'pitstop-aks-cluster'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build All Services
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build all services that have a Dockerfile
          for service_dir in src/*/; do
            if [ -f "${service_dir}Dockerfile" ]; then
              service_name=$(basename $service_dir)
              service_name_lower=$(echo "$service_name" | tr '[:upper:]' '[:lower:]')
              echo "Building $service_name_lower from $service_dir"
              docker build -t $DOCKERHUB_USERNAME/pitstop-$service_name_lower:$IMAGE_TAG -f ${service_dir}Dockerfile ${service_dir}
              docker push $DOCKERHUB_USERNAME/pitstop-$service_name_lower:$IMAGE_TAG
            fi
          done

      - name: Install Istio Control Plane
        run: |
          curl -L https://istio.io/downloadIstio | sh -
          export PATH="$HOME/.istioctl/bin:$PATH"
          cd src/k8s/istio
          chmod +x *.sh
          ./install-istio.sh

      - name: Deploy All Services to AKS
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd src/k8s/scripts
          chmod +x start-all.sh
          # Pass the Istio flag and the new tag to the deployment script
          ./start-all.sh --istio --tag $IMAGE_TAG